[build]
  command = "pnpm install"
  publish = "."  

[[functions]]
  directory = "."  # This tells Netlify to look in the root directory for your serverless functions (like `index.mjs`)

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[redirects]]
  from = "/frame"
  to = "/index.mjs"  # Route `/frame` to your serverless function (`index.mjs`)
  status = 200
  force = true