[build]
  command = "pnpm install"
  publish = "public"  # Serve static assets from `public/` folder

[[functions]]
  directory = "."  # Assuming `index.mjs` is in the root directory

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"

[[redirects]]
  from = "/frame"
  to = "/index.mjs"  # Point to the `index.mjs` serverless function
  status = 200
  force = true